// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ8-qhIqr5jst4SohQcmcb9pA7YUZR-G0',
    appId: '1:569987428108:web:49899ca18adf43d9a46329',
    messagingSenderId: '569987428108',
    projectId: 'searchino-e832b',
    authDomain: 'searchino-e832b.firebaseapp.com',
    storageBucket: 'searchino-e832b.appspot.com',
    measurementId: 'G-9LQS2MW232',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD19NGW-1GoxZWh1lwp59G6Ixh_HdycxRk',
    appId: '1:569987428108:android:dda7eb751d939f77a46329',
    messagingSenderId: '569987428108',
    projectId: 'searchino-e832b',
    storageBucket: 'searchino-e832b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEARoDZLWMvAqpIYxwWuFj10PgIR-f00Q',
    appId: '1:569987428108:ios:b31b472abd00bb94a46329',
    messagingSenderId: '569987428108',
    projectId: 'searchino-e832b',
    storageBucket: 'searchino-e832b.appspot.com',
    iosClientId: '569987428108-veu7f1kmtm2dbk3maie7srqd43jge9vd.apps.googleusercontent.com',
    iosBundleId: 'com.example.searchino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEARoDZLWMvAqpIYxwWuFj10PgIR-f00Q',
    appId: '1:569987428108:ios:5e518f22cfe28a64a46329',
    messagingSenderId: '569987428108',
    projectId: 'searchino-e832b',
    storageBucket: 'searchino-e832b.appspot.com',
    iosClientId: '569987428108-mjh1eng8uijs3jg0rjbqrirr135d3sg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.searchino.RunnerTests',
  );
}
